#
#                                      / \  //\
#    LightMine           |\___/|      /   \//  \\
#     Development        /0  0  \__  /    //  | \ \
#                       /     /  \/_/    //   |  \  \
#                       @_^_@'/   \/_   //    |   \   \
#                       //_^_/     \/_ //     |    \    \
#                    ( //) |        \///      |     \     \
#  By              ( / /) _|_ /   )  //       |      \     _\
#   Riku           ( // /) '/,_ _ _/  ( ; -.    |    _ _\.-~        .-~~~^-.
#              (( / / )) ,-{        _      `-.|.-~-.           .~         `.
#             (( // / ))  '/\      /                 ~-. _ .-~      .-~^-.  \
#             (( /// ))      `.   {            }                   /      \  \
#              (( / ))     .----~-.\        \-'                 .~         \  `. \^-.
#                         ///.----..>        \             _ -~             `.  ^-`  ^-_
#                            ///-._ _ _ _ _ _ _}^ - - - - ~                     ~-- ,.-~
#                                                                              /.-~
#
#
#              .              _       .        .
#              /     `   ___. /      _/_      /|    .___  .___    __.  ,  _  /   ____
#              |     | .'   ` |,---.  |      /  \   /   \ /   \ .'   \ |  |  |  (
#              |     | |    | |'   `  |     /---'\  |   ' |   ' |    | `  ^  '  `--.
#              /---/ /  `---| /    |  \__/,'      \ /     /      `._.'  \/ \/  \___.'
#                       \___/
#
# TNT - Вызывает взрыв динамита.
# CLEAN - Снимает все эффекты с игрока.
# CHANGE - Меняет при попадании игроков местами.
# AIM - Самонаводящаяся стрела.
# MIXITEMS - Меняет предметы в правой и левой руке местами.
# BLACKHOLE-N - Притягивает игроков радиусе N блоков.
# etc.
#
# Флаги:
#  HIDE_ATTRIBUTES, Скрывает атрибуты
#  HIDE_ENCHANTS, Скрывает зачарования
#  HIDE_POTION_EFFECTS. Скрывает эффекты зелий
#
# Эффекты:
#  https://helpch.at/docs/1.12.2/org/bukkit/potion/PotionEffectType.html
# f
LightArrows:
  TNT:
    name: '&cВзрывная стрела'
    meta: 'TNT'
    color: '#b82525'
    lore:
      - ''
      - '&cВзрывает игрока при попадании'
      - ''
    effects:
      - 'LEVITATION,100,1'
    flags:
      - 'HIDE_POTION_EFFECTS'

  CHANGE:
    name: '&cСтрела обмена'
    meta: 'CHANGE'
    color: '#822eff'
    lore:
      - ''
      - '&cПри попадании меняет местами игрока и противника'
      - ''
    effects:
      - 'WITHER,100,1'
    flags:
      - 'HIDE_POTION_EFFECTS'

  CLEAR:
    name: '&cОчищающая стрела'
    meta: 'CLEAR'
    color: '#FFFF00'
    lore:
      - ''
      - '&cПри попадании очищает эффекты у игрока'
      - ''
    effects:
      - 'WITHER,100,2'
    flags:
      - 'HIDE_POTION_EFFECTS'

  AIM:
    name: '&cСамонаводящаяся стрела'
    meta: 'AIM'
    color: '#FFFF00'
    lore:
      - ''
      - '&fМоментальный урон &cII'
      - '&fНаводка &cII'
      - ''
    effects:
      - 'HARM,10,1'
    flags:
      - 'HIDE_POTION_EFFECTS'

  MIXITEMS:
    name: '&cСамонаводящаяся стрела'
    meta: 'MIXITEMS'
    color: '#FFFF00'
    lore:
      - ''
      - '&fМеняет предметы в руках местами.'
      - ''
    effects: []
    flags:
      - 'HIDE_POTION_EFFECTS'

  BLACKHOLE:
    name: '&cСтрела черной дыры'
    meta: 'BLACKHOLE-30'
    color: '#000000'
    lore:
      - ''
      - '&fПритягивает окружающих игроков в радиусе 30-и блоков.'
      - ''
    effects: []
    flags:
      - 'HIDE_POTION_EFFECTS'